[package]
name = "peeps-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
compact_str.workspace = true
facet.workspace = true
facet-json.workspace = true
facet-value.workspace = true
ureq.workspace = true
