[package]
name = "moire-trace-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
rusqlite = ["dep:rusqlite"]

[dependencies]
facet.workspace = true
rusqlite = { workspace = true, optional = true }
