[workspace]
resolver = "2"
members = [
  "crates/peeps",
  "crates/peeps-locks",
  "crates/peeps-tasks",
  "crates/peeps-threads",
  "crates/peeps-types",
  "crates/peeps-sync",
  "crates/peeps-web",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bearcove/peeps"

[workspace.dependencies]
# Internal
peeps = { path = "crates/peeps" }
peeps-locks = { path = "crates/peeps-locks" }
peeps-tasks = { path = "crates/peeps-tasks" }
peeps-threads = { path = "crates/peeps-threads" }
peeps-types = { path = "crates/peeps-types" }
peeps-sync = { path = "crates/peeps-sync" }
peeps-web = { path = "crates/peeps-web" }

# External
backtrace = "0.3"
inventory = "0.3"
facet = { git = "https://github.com/facet-rs/facet", branch = "main" }
facet-json = { git = "https://github.com/facet-rs/facet", branch = "main" }
libc = "0.2"
parking_lot = "0.12"
roam-session = { path = "../roam/rust/roam-session", features = ["diagnostics"] }
roam-shm = { path = "../roam/rust/roam-shm", features = ["diagnostics"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.49", features = ["full"] }
axum = { version = "0.8", features = ["ws"] }
rust-embed = "8"
mime_guess = "2"
