[package]
name = "peeps-sync"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
peeps-tasks.workspace = true
peeps-types.workspace = true
tokio.workspace = true

[features]
diagnostics = ["peeps-tasks/diagnostics"]
