[package]
name = "peeps-source"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
rusqlite = ["dep:rusqlite"]

[dependencies]
facet.workspace = true
camino.workspace = true
rusqlite = { workspace = true, optional = true }
