[package]
name = "peeps-locks"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
diagnostics = []

[dependencies]
facet.workspace = true
parking_lot.workspace = true
tokio.workspace = true
