[package]
name = "moire-backtrace-poc-leaf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
moire-trace-capture.workspace = true
moire-trace-types.workspace = true
