[package]
name = "peeps-sqlite-facet"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
compact_str.workspace = true
facet-json.workspace = true
facet-value.workspace = true
peeps-types.workspace = true
rusqlite.workspace = true
