[package]
name = "peeps"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
locks = ["dep:peeps-locks"]
diagnostics = ["peeps-tasks/diagnostics", "peeps-threads/diagnostics", "peeps-locks?/diagnostics", "peeps-sync/diagnostics"]

[dependencies]
facet.workspace = true
facet-json.workspace = true
peeps-locks = { workspace = true, optional = true }
peeps-sync.workspace = true
peeps-tasks.workspace = true
peeps-threads.workspace = true
peeps-types.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
